apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
        - name: spring-helloworld
          image: zagorgent/spring-helloworld:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-helloworld-service
spec:
  selector:
    app: spring-helloworld
  ports:
    - protocol: TCP
      port: 80  # The port on which the service will be exposed externally
      targetPort: 8080  # The port on which the application is running inside the pod
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer (you can also use NodePort or ClusterIP)
